spring:
  application:
    name: slg-client
  ai:
    mcp:
      server:
        type: SYNC
        name: slg-client
        version: 1.0.0

server:
  port: 8099

client:
  server-url: ws://localhost:50001/ws

table:
  path: table
